### ISSUE TITLE
AlwaysRecoverAllItemsFromTacticalMissions broken in 1.11

### ISSUE THREAD

**Issue by paulgrove** [Mad-Mods-Phoenix-Point/AssortedAdjustments#11]
I visited a scavenging mission with this feature enabled.

The briefing page still mentioned requiring to pickup resources, when I started the missing I evacuated immediately and the resources were not recovered.

As per the description for this feature I think the above test case should have recovered the resources.

**Comment by mad2342** [comment]
Iirc that feature still needed items to be "explored", as in containers opened/enemies killed. you just don't have to carry them to the dropship...

**Comment by paulgrove** [comment]
OK thanks, I will re-test

**Comment by paulgrove** [comment]
Yes this worked - just not how I expected.  The resources I left on the floor were not received - but all the other items In the opened container were received.
