### ISSUE TITLE
EnhanceSpecialRecruits not working well with the size of the Aircraft space

### ISSUE THREAD

**Issue by hiloyt** [Mad-Mods-Phoenix-Point/AssortedAdjustments#12]
When "EnhanceSpecialRecruits" is set to "true", any changes done in the "Aircraft<name>Space" not working in the game.

Is this the expected result?

This works the same with the old save and the new one.

PP: 1.13.72080
Modnix: 2.5.7
AA: 1.12.0.0

**Comment by mad2342** [comment]
Hi hiloyt,
I suspect a more generic issue with PP 1.13.X and AA 1.12.X with you reported issue as a side effect.
I never had any issues with your stated combination of settings, i use them both in conjunction too.
As i still have to wait for current patch of PP on GOG it'll take a moment before i can check AA against 1.13.X.
Best regards, Mad

**Comment by mad2342** [comment]
PP 1.13 added a method overload for unit generation, this broke patching if "EnhanceSpecialRecruits" was enabled.
Fixed with 1.13.0.0
