### ISSUE TITLE
FastMetabolism is enabled in vanilla preset and does not use EnableSoldierAdjustments 

### ISSUE THREAD

**Issue by NBKRedSpy** [Mad-Mods-Phoenix-Point/AssortedAdjustments#13]
FastMetabolism is enabled when the vanilla preset is used.  I would expect this to be false by default for the vanilla preset.

Also, the settings-reference.htm appears to group FastMetabolism under EnableSoldierAdjustments, however the code doesn't look at EnableSoldierAdjustments.

Very low priority since it is easy to turn off.

**Comment by NBKRedSpy** [comment]
I have a patch I'm testing right now which just adds a EnableSoldierAdjustments settings check to the FastMetabolism settings check.  If you are ok with that, I can submit a pull request.

**Comment by mad2342** [comment]
PR is merged, will be part of next release.
