### ISSUE TITLE
Recruiting Mutoids breaks UI.

### ISSUE THREAD

**Issue by mad2342** [Mad-Mods-Phoenix-Point/AssortedAdjustments#14]
> Can't figure out exactly why, but while using this mod, I can't recruit any Mutoids. I recruit them and then my mouse stops working.

(squidney2k1)

**Comment by NBKRedSpy** [comment]
thevoidseeker says that he only ran into this with "select class trait mod".  Asked squidney2k1 if he had any other mods enabled on nexusmods.

**Comment by mad2342** [comment]
Was an issue with another mod. Nothing to be done here.
