### ISSUE TITLE
1.10 Orryx SmartEvacuation patch (diff and build)

### ISSUE THREAD

**Issue by Sheep-y** [Mad-Mods-Phoenix-Point/AssortedAdjustments#2]
I found an error for SmartEvacuation because `TacticalView.ShowExitMissionPrompt` no longer exists, causing `Harmony.PatchAll` to abort early.

The closest I found is `OnAbilityExecuted`, which is less specific so I added a parameter and gated it.

Here is my [diff](https://github.com/Mad-Mods-Phoenix-Point/AssortedAdjustments/files/5943916/1-10-fix.diff.zip) and [my build](https://github.com/Mad-Mods-Phoenix-Point/AssortedAdjustments/files/5943917/AssortedAdjustments.zip), which seems to have the basic features working (including smart evac) on default settings.

**Comment by mad2342** [comment]
Thx Sheepy for your help!
Finally have the update myself and fixed it.
