### ISSUE TITLE
Can the mod be applied to saved games 

### ISSUE THREAD

**Issue by jonnieb007** [Mad-Mods-Phoenix-Point/AssortedAdjustments#3]
I have installed the mod but the changes does seem to appear in my existing games, does it only work for new games?

**Comment by mad2342** [comment]
Hi jonnieb007,
Almost everything works instantly and doesn't require a new game. Some things need the appropriate triggers to kick in (recruit-gen and similar) and won't change stuff retroactively but apart from that...
Please check Modnix logs and AssortedAdjustments.log for possible entries, thx!
Best regards, Mad

**Comment by jonnieb007** [comment]
[AssortedAdjustments @ 25/03/2021 11:23:11] CLEANED UP
[AssortedAdjustments @ 25/03/2021 11:23:11] Logger.Initialize(C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\AssortedAdjustments\AssortedAdjustments.log, 1, C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\AssortedAdjustments, AssortedAdjustments)
[AssortedAdjustments @ 25/03/2021 11:23:11] Modnix Mad.AssortedAdjustments.SplashMod initialised.
----------------------------------------------------------------------------------------------------
[AssortedAdjustments @ 25/03/2021 11:23:26] EXCEPTION:
Message: Exception has been thrown by the target of an invocation.<br/>
StackTrace:   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <9577ac7a62ef43179789031239ba8798>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
  at Harmony.PatchProcessor.RunMethod[S,T] (T defaultIfNotExisting, System.Object[] parameters) [0x00150] in <ef472ad41f4948fdb52674edfe069979>:0 
  at Harmony.PatchProcessor.PrepareType () [0x000e4] in <ef472ad41f4948fdb52674edfe069979>:0 
  at Harmony.PatchProcessor..ctor (Harmony.HarmonyInstance instance, System.Type type, Harmony.HarmonyMethod attributes) [0x00065] in <ef472ad41f4948fdb52674edfe069979>:0 
  at Harmony.HarmonyInstance.<PatchAll>b__9_0 (System.Type type) [0x00023] in <ef472ad41f4948fdb52674edfe069979>:0 
  at Harmony.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) [0x0001b] in <ef472ad41f4948fdb52674edfe069979>:0 
  at Harmony.HarmonyInstance.PatchAll (System.Reflection.Assembly assembly) [0x00007] in <ef472ad41f4948fdb52674edfe069979>:0 
  at Harmony.HarmonyInstance.PatchAll () [0x0001e] in <ef472ad41f4948fdb52674edfe069979>:0 
  at AssortedAdjustments.AssortedAdjustments.MainMod (System.Func`3[T1,T2,TResult] api) [0x00005] in <cab15251920e4c54999f6d24d40ded60>:0 
----------------------------------------------------------------------------------------------------

**Comment by jonnieb007** [comment]
11:23:11.0571 INFO Sheepy.Modnix.ModLoader/2.5.7.0; 2021-03-25 11:23:11Z
11:23:11.0651 INFO Assembly-CSharp/1.10.1.67450
11:23:11.0983 INFO Loading C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\Modnix.conf
11:23:11.5085 INFO Scanning for mods: C:\Users\macadm\Documents\My Games\Phoenix Point\Mods
11:23:11.5595 INFO Found mod ConsoleEnabler at C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\ConsoleEnabler.dll (1 dlls)
11:23:11.5715 INFO Ignoring Logger.Initialize because not IPhoenixPointMod
11:23:11.5985 INFO Found mod Mad.AssortedAdjustments at C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\AssortedAdjustments\AssortedAdjustments.dll (1 dlls)
11:23:11.6015 INFO Found mod Sheepy.DumpData at C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\PhoenixPt_DumpData\PhoenixPt_DumpData.dll (1 dlls)
11:23:11.6045 INFO Found mod PhoenixPointRetrievableItems at C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\Retrievable Items 1.2-8-1-2\PhoenixPointRetrievableItems.dll (1 dlls)
11:23:11.6055 INFO Resolving 4 mods
11:23:11.6105 INFO 4 mods found, 4 enabled.
11:23:11.6105 INFO PHASE SplashMod
11:23:11.6115 INFO Loading C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\AssortedAdjustments\AssortedAdjustments.dll
11:23:11.6806 INFO Calling AssortedAdjustments.AssortedAdjustments.SplashMod(Func`3) in C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\AssortedAdjustments\AssortedAdjustments.dll
11:23:25.8510 INFO PHASE Init
11:23:25.8510 INFO Loading C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\ConsoleEnabler.dll
11:23:25.8520 INFO Calling ConsoleEnabler.ConsoleEnable.Init() in C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\ConsoleEnabler.dll
11:23:25.8630 INFO PHASE Initialize
11:23:25.8630 INFO Loading C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\Retrievable Items 1.2-8-1-2\PhoenixPointRetrievableItems.dll
11:23:25.8650 INFO Loading embedded PPML
11:23:25.8778 EROR PhoenixPointRetrievableItems┊System.TypeLoadException: Could not resolve the signature of a virtual method
  at (wrapper managed-to-native) System.RuntimeType.GetMethodsByName_native(System.RuntimeType,intptr,System.Reflection.BindingFlags,bool)
  at System.RuntimeType.GetMethodsByName (System.String name, System.Reflection.BindingFlags bindingAttr, System.Boolean ignoreCase, System.RuntimeType reflectedType) [0x0001b] in <9577ac7a62ef43179789031239ba8798>:0 
  at System.RuntimeType.GetMethodCandidates (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.CallingConventions callConv, System.Type[] types, System.Boolean allowPrefixLookup) [0x00010] in <9577ac7a62ef43179789031239ba8798>:0 
  at System.RuntimeType.GetMethods (System.Reflection.BindingFlags bindingAttr) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
  at Sheepy.Modnix.ModLoader.CallInit (Sheepy.Modnix.ModEntry mod, System.Reflection.Assembly dll, System.String typeName, System.String methodName) [0x0004b] in <e693e892a024434e89be0225bb0085c2>:0 
11:23:25.8858 INFO PHASE MainMod
11:23:25.8858 INFO Calling AssortedAdjustments.AssortedAdjustments.MainMod(Func`3) in C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\AssortedAdjustments\AssortedAdjustments.dll
11:23:26.0490 INFO Loading C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\PhoenixPt_DumpData\PhoenixPt_DumpData.dll
11:23:26.0490 INFO Calling Sheepy.PhoenixPt.DumpData.Mod.MainMod(Func`3) in C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\PhoenixPt_DumpData\PhoenixPt_DumpData.dll
11:23:26.0530 INFO Sheepy.DumpData┊Buiding type map
11:23:26.0870 INFO Sheepy.DumpData┊Registered api 'dump.xml'
11:23:26.0880 INFO Sheepy.DumpData┊Dumping data to C:\Users\macadm\Documents\My Games\Phoenix Point\Mods\PhoenixPt_DumpData
11:23:26.0880 INFO Sheepy.DumpData┊Scanning data
11:23:26.1260 INFO Sheepy.DumpData┊Scanning text
11:23:26.1300 WARN Sheepy.DumpData┊'Dump_Others' requires Scripting Library or other mod that provides the 'eval.cs' api.  Delete it from config to remove this warning.
11:23:26.1300 INFO Sheepy.DumpData┊42791 entries to dump
11:23:26.1310 INFO Sheepy.DumpData┊Dumping Data-ComponentSetDef (91)
11:23:26.1310 INFO Sheepy.DumpData┊Dumping Data-SpecializationDef (7)
11:23:26.1320 INFO Sheepy.DumpData┊Dumping Data-AbilityTrackDef (7)
11:23:26.1320 INFO Sheepy.DumpData┊Dumping Data-AbilityDef (422)
11:23:26.1320 INFO Sheepy.DumpData┊Dumping Data-GeoActorDef (11)
11:23:26.1320 INFO Sheepy.DumpData┊Dumping Data-GeoMistGeneratorDef (1)
11:23:26.1320 INFO Sheepy.DumpData┊Dumping Data-GeoscapeEventDef (545)
11:23:26.1320 INFO Sheepy.DumpData┊Dumping Data-GameTagDef (497)
11:23:26.1320 INFO Sheepy.DumpData┊Dumping Data-AchievementDef (48)
11:23:26.1551 INFO Sheepy.DumpData┊Dumping Data-GeoFactionDef (8)
11:23:26.1551 INFO Sheepy.DumpData┊Dumping Data-GeoAlienBaseDef (1)
11:23:26.1631 INFO Sheepy.DumpData┊Dumping Data-GeoHavenZoneDef (14)
11:23:26.1671 INFO Sheepy.DumpData┊Dumping Data-GroundVehicleItemDef (11)
11:23:26.1691 INFO Sheepy.DumpData┊Dumping Data-VehicleItemDef (4)
11:23:26.1741 INFO Sheepy.DumpData┊Dumping Data-TacMissionTypeDef (305)
11:23:26.2051 INFO Sheepy.DumpData┊Dumping Data-PhoenixFacilityDef (28)
11:23:26.2531 INFO Sheepy.DumpData┊Dumping Data-ResearchDef (315)
11:23:26.3002 INFO Sheepy.DumpData┊Dumping Data-TacticalActorDef (37)
11:23:26.3342 INFO Sheepy.DumpData┊Dumping Data-DamageKeywordDef (25)
11:23:26.4753 INFO Sheepy.DumpData┊Dumping Data-TacticalItemDef (793)
11:23:26.5064 INFO Sheepy.DumpData┊Dumping Data-BodyPartAspectDef (552)
11:23:26.5484 INFO Sheepy.DumpData┊Dumping ConsoleCommand (288)
11:23:26.5734 INFO Sheepy.DumpData┊Dumping Guid (17436)
11:23:26.8126 INFO Sheepy.DumpData┊Dumping Text-I2LocPhoenixPoint (10255)
11:23:26.8757 INFO Sheepy.DumpData┊Dumping Text-I2LocPhoenixPoint_CharNames (2619)
11:23:26.9608 INFO Sheepy.DumpData┊Dumping Text-I2LocPhoenixPoint_GeoEvents_DLC1 (5541)
11:23:27.2450 INFO Sheepy.DumpData┊Dumping Text-I2LocPhoenixPoint_GeoHavens (1469)
11:23:27.2971 INFO Sheepy.DumpData┊Dumping Text-I2LocPhoenixPoint_Research (1461)
11:23:29.0983 INFO Sheepy.DumpData┊42791 entries dumped

**Comment by jonnieb007** [comment]
Looks like there are some issues

**Comment by mad2342** [comment]
For the first comment there's a problem with harmony not finding some method, may i ask which version of game/aa/modnix you're using?
For the second, the mod "PhoenixPointRetrievableItems" breaks stuff, not AA so it seems...

**Comment by jonnieb007** [comment]
PP 1.10.1 
AA v 1.10.1.3
modnix 2.5.7

**Comment by jonnieb007** [comment]
disabled "PhoenixPointRetrievableItems" now working

MaxAugmentations now 3 - yippee 

Suggested update - be able to add 3 mutations would be nice 

Cheers

**Comment by jonnieb007** [comment]
my mistake it seems 3 mutations is working

**Comment by mad2342** [comment]
so, no problem with AA itself, just domino-effect?
Kewl, closing.
