### ISSUE TITLE
Version 1.11 appears to have broken the mod

### ISSUE THREAD

**Issue by sadhukar** [Mad-Mods-Phoenix-Point/AssortedAdjustments#4]
Alot of adjustments, like bases and aircraft, are no longer working

**Comment by paulgrove** [comment]
Hi sadhukar / anyone else out there, I too would like to see this mod updated.

I am unfortunately not well versed in c#, however I do know c and c++ among other languages.

I am currently getting an environment setup to try and work on this, and am looking at dnSpy, Harmony and the Modnix API to see how I fare (which may or may not go well).

I suggest that we go through all of the mod features, enabling one at a time to gather information on which features are broken and in what way. We can create individual tickets for these issues.

This should be very helpful should the original developer return, and also will be a good place for me or others to start investigating fixes for these problems.

**Comment by sadhukar** [comment]
Hi Paul!

Thank you for that offer. I have the opposite problem with you - I'm ok with C#, but I don't have a home environment since I only use it for work. 

I have a suspicion that the issue might be deeper than this addon, that is to say, the injectors themselves (modnix or whatnot) need to be updated as Snapshot has changed some variables around. But since you actually have studio and dnSpy you're probably in a better position to tell us :)

**Comment by mad2342** [comment]
Finally tested this stuff with current game version on GOG, for me everything seems to be in order.
Closing this issue, feel free to open another if problems persist.
