### ISSUE TITLE
ShowExtendedBaseInfo broken in 1.11

### ISSUE THREAD

**Issue by paulgrove** [Mad-Mods-Phoenix-Point/AssortedAdjustments#7]
Polaris 1.11 EGS
AssortedAdjustments 1.10.1.4
Modnix 2.5.7

With ShowExtendedBaseInfo enabled:

![image](https://user-images.githubusercontent.com/184906/119737022-8b743800-be76-11eb-8555-d8c191c8a546.png)

Tooltips in geoscape look good.
I am uncertain on the "bases info in recruitment screen" part of this feature description - I cannot see any difference on the recruits page with it enabled or not.

**Comment by mad2342** [comment]
Fixed since 1.11.0.0.
Closing this issue, feel free to open another if problems persist.
