### ISSUE TITLE
ShowDetailedResearchAndProduction not working in 1.11 - conflicts with Agenda Tracker

### ISSUE THREAD

**Issue by paulgrove** [Mad-Mods-Phoenix-Point/AssortedAdjustments#8]
No change to Facility display, also breaks (no longer visible) the AgendaTracker

I noticed after some testing that the Agenda Tracker was not working, so disabled each UI Enhancement until I found the culprit - only ShowDetailedResearchAndProduction causes this issue.

**Comment by mad2342** [comment]
Finally tested this stuff with current game version on GOG, for me everything seems to be in order.
Closing this issue, feel free to open another if problems persist.
