### ISSUE TITLE
All vehicle features broken in 1.11

### ISSUE THREAD

**Issue by paulgrove** [Mad-Mods-Phoenix-Point/AssortedAdjustments#9]
No effect is seen when enabling these features.

**Comment by paulgrove** [comment]
It has been reported that AircraftManticoreSpace alone works in #5 by two people.

**Comment by jarnomikkola1** [comment]
> It has been reported that AircraftManticoreSpace alone works in #5 by two people.

No, that's incorrect. As at least it WORKS, but only so in the Epic Games Store game. It doesn't work in the Steam version. 
And we have no idea, of the "why". Well, except that the EGS game is the most compatible with this mod, while the others are far less( assumed from the Steam being very incompatible). To know the exact extent, is still to be proceduraly found out. 

Ouh, by the way, also the Manticore speed and flying lenght works too ... I have a highly cheated game, and all of that works. Cause I want to have 1 team... like in XCOM.

**Comment by mad2342** [comment]
Finally tested this stuff with current game version on GOG, for me everything seems to be in order.
I have no idea why the Steam version would behave differently once Modnix and AA itself get loaded without errors as there are no indications that there's platform dependent code.
Closing this issue, feel free to open another if problems persist.
